cloud_app_dev/week10/authenticationApp/config/routes.rb
Rails.application.routes.draw do
  resources :todos
  devise_for :users
  resources :users
  root to: "home#index"
  get 'home/index'
 
   
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

cloud_app_dev/week10/authenticationApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <div>Signed in as...
        <%= current_user.email %>
        <%= link_to 'Todos', todos_url, :method => :get%>
        (<%= link_to 'Sign out', destroy_user_session_path, :method => :get%>)
      </div>
    <% else %>
      <%= link_to 'Register', new_user_registration_path %> or
      <%= link_to 'Sign in', new_user_session_path %>
    <% end %>

  
    <%= yield %>
  </body>
</html>